project2:
  outputs:
    dev:
      account: qi29186.europe-west2.gcp
      database: project2
      password: Yb5wRktza6kdmnV
      role: accountadmin
      schema: project_schema
      threads: 1
      type: snowflake
      user: BLUEFLAKE
      warehouse: compute_wh
  target: dev
